### PR TITLE
Add anthropic provider 

### PR DESCRIPTION
**Pull request by nmnduy**
- add anthropic provider
- fix cannot override provider

### CODE REVIEW

**Comment by kaihendry** [comment]
Was playing with this by setting `vim.g["codegpt_llm_api_provider"] = "anthropic"` (is there an easier toggle?), though I hit

> Error: 404 {"type":"error","error":{"type":"not_found_error","message":"model: gpt-3.5-turbo"}}

**Comment by nmnduy** [comment]
> Was playing with this by setting `vim.g["codegpt_llm_api_provider"] = "anthropic"` (is there an easier toggle?), though I hit
> 
> > Error: 404 {"type":"error","error":{"type":"not_found_error","message":"model: gpt-3.5-turbo"}}

`gpt-3.5-turbo` is not an anthropic model.

You need set config to another model that Anthropic provides. Also, an Anthropic API key is required.

**Comment by dpayne** [comment]
I do not use Anthropic but I am sure others will appreciate it, thank you!

**Comment by dpayne** [comment]
some slight changes were made, I renamed the config to just "codegpt_api_provider" as well as adding a fallback for the old config.

**Pull request merged**
