### PR TITLE
popup commands

### PR DESCRIPTION
**Pull request by 00sapo**
This pull request introduces custom popup commands and 2 new default commands for popup windows, namely:
* C-o to use the popup content as output (replacing the lines)
* C-i to use the popup content as input of a new API call (selecting the whole content and prompting to the command line)

It actually also solves an existing problem when the user changes the buffer before the answer arrives: this pull request solves the issue by computing the point where the lines should be changed before running the request.

### CODE REVIEW

**Comment by dpayne** [comment]
I think this is a good idea. One comment, if a user user C-i and then immediately closes the window I get an error `CodeGPT.nvim/lua/codegpt/utils.lua:52: Invalid buffer id: 11`. Would it be possible to try to detect this (maybe by checking if the popup window is open)? If the popup is closed, then re-open it and paste the contents in the new popup.

**Comment by 00sapo** [comment]
I'm not aure I'm understanding your point. Could you please explain key by key what you mean?

**Comment by dpayne** [comment]
I went ahead implemented what I was trying to say here https://github.com/dpayne/CodeGPT.nvim/commit/8bce918ee8a33bcb851873439c44d9ca723d7c28 .

Please let me know if you see anything wrong/broken with it. This is a feature I did not really think about so I appreciate the PR, thank you!

**Comment by 00sapo** [comment]
I got the point. I wasn't experiencing it because I'm only using popup windows... Thanks for merging!

**Pull request merged**
